### ISSUE TITLE
Conv in onnx-mxnet / convolution operator in MXNet

### ISSUE THREAD

**Issue by HeliWang** [onnx/onnx-mxnet#39] opened 2018-03-08 00:41 UTC
The issue might be more related to MXNet itself. Really appreciate if you can help.
I am trying to convert such a CNN model using onnx-mxnet:
![cnncnccn](https://user-images.githubusercontent.com/12112939/37126610-c811c6e6-223f-11e8-87ea-0fb0dffa42f2.png)

Such an exception occurs when running the convolution operator:
"mxnet-build\src\operator\./convolution-inl.h:625: Check failed: dtype != -1 (-1 vs. -1) First input must have specified type"

Seems like dtype is undefined. Any suggestion in solving the issue?
Thanks 
![ecept](https://user-images.githubusercontent.com/12112939/37126510-56a59406-223f-11e8-85fc-22c29712faf5.png)

**Comment by anirudhacharya** [comment] 2018-03-08 01:02
@HeliWang Can you share a short script that reproduces the error. Or, please provide link to the existing example or share the onnx model for the above network.

Also, paste the commands you ran that produced the error.

@spidyDev is this related to the bug fix you are working on?

**Comment by HeliWang** [comment] 2018-03-09 06:00
Let me update later here. Before the error could be reproduced, let me make some pull request of some changes I made to the codebase of onnx-mxnet, for example, implementing the Gather operator by take. Afterwards I will update the procedure of reproducing the error here.

**Comment by anirudhacharya** [comment] 2018-03-09 20:55
@HeliWang feel free to make the PRs. If you plan on making a PR a week or two later, then you should probably consider making a PR against the incubator-mxnet repo once this PR - https://github.com/apache/incubator-mxnet/pull/9963 gets merged.

**Comment by anirudhacharya** [comment] 2018-04-01 00:50
Closing this issue due to inactivity, if you still face this issue feel free to reopen this.

**Closed by anirudhacharya** 2018-04-01 00:50 UTC
Labels: Pending requester info
