### ISSUE TITLE
Inconsistent Shape

### ISSUE THREAD

**Issue by Rizhiy** [onnx/onnx-mxnet#12] opened 2017-12-20 12:34 UTC
When I try to load model saved with pytorch, I get:
```
Traceback (most recent call last):
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd-mkl/lib/python3.6/site-packages/mxnet/symbol/symbol.py", line 1488, in simple_bind
    ctypes.byref(exe_handle)))
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd-mkl/lib/python3.6/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator fullyconnected0: Shape inconsistent, Provided=[1024,2048], inferred shape=(1024,8192)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reid.py", line 15, in <module>
    mod.bind(for_training=False, data_shapes=[('input_0', test_image.shape)], label_shapes=None)
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd-mkl/lib/python3.6/site-packages/mxnet/module/module.py", line 428, in bind
    state_names=self._state_names)
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd-mkl/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 237, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd-mkl/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 333, in bind_exec
    shared_group))
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd-mkl/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 611, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd-mkl/lib/python3.6/site-packages/mxnet/symbol/symbol.py", line 1494, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
input_0: (1, 3, 256, 128)
Error in operator fullyconnected0: Shape inconsistent, Provided=[1024,2048], inferred shape=(1024,8192)
```

[Model used](https://drive.google.com/open?id=1Ip87G-Cuh1HB7LDD2d674qmeDF-Ql8Sl)

Script used to load the model:
```python
import onnx_mxnet
from PIL import Image

import os.path as osp
import numpy as np
import mxnet as mx

from collections import namedtuple

sym, params = onnx_mxnet.import_model('model.onnx')

test_image = np.random.rand(256, 128, 3).transpose((2, 0, 1))[np.newaxis, :, :, :]

mod = mx.mod.Module(symbol=sym, data_names=['input_0'], context=mx.cpu(), label_names=None)
mod.bind(for_training=False, data_shapes=[('input_0', test_image.shape)], label_shapes=None)
mod.set_params(arg_params=params, aux_params=None, allow_missing=True)

Batch = namedtuple('Batch', ['data'])
mod.forward(Batch([mx.nd.array(test_image)]))
output = mod.get_outputs()
```

Can you tell me what is wrong? Is the problem with mxnet import or pytorch export?

**Comment by Rizhiy** [comment] 2017-12-21 15:47
It appears that pooling layers are not working properly.

**Comment by Rizhiy** [comment] 2017-12-25 13:32
The problem was with the definition of the max pooling layer. `pooling_convention` was set to `full` instead of `valid`.
I'm not sure if the problem is with how Pytorch saves onnx or how you load it, so I will leave this open for now.

**Comment by lupesko** [comment] 2018-01-03 19:40
Thanks @Rizhiy - it seems that the issue is with the onnx-mxnet converter that uses the wrong pooling_convention arg for MXNet Pooling.

@Roshrini can you please look into making the change? can we also have a unit test that checks for this layer?

Assigning to @Roshrini and labeling as a bug.

**Comment by Roshrini** [comment] 2018-01-03 19:48
In definition of the max pooling layer, `pooling_convention` was set to `full` instead of `valid` according to caffe2. Caffe2 uses `full` and pytorch seems to use `valid`.. will need to figure it out to make it work for all the models.

**Comment by Rizhiy** [comment] 2018-02-28 22:58
@hdjsjyl Read my comments.

**Comment by hdjsjyl** [comment] 2018-02-28 23:13
@Rizhiy , thanks

**Comment by anirudhacharya** [comment] 2018-03-31 18:08
@Rizhiy @hdjsjyl Please check with the latest master of mxnet - https://github.com/apache/incubator-mxnet. I ran the following code with your model, and it seems to work fine.

```python
import mxnet as mx
from mxnet.contrib import onnx as onnx_mxnet
from PIL import Image

import os.path as osp
import numpy as np
import mxnet as mx

from collections import namedtuple

sym, arg, aux = mx.contrib.onnx.import_model('model.onnx')

test_image = np.random.rand(256, 128, 3).transpose((2, 0, 1))[np.newaxis, :, :, :]

mod = mx.mod.Module(symbol=sym, data_names=['input_0'], context=mx.cpu(), label_names=None)
mod.bind(for_training=False, data_shapes=[('input_0', test_image.shape)], label_shapes=None)
mod.set_params(arg_params=arg, aux_params=aux, allow_missing=True)

Batch = namedtuple('Batch', ['data'])
mod.forward(Batch([mx.nd.array(test_image)]))
output = mod.get_outputs()
print(output)
```

Please reopen the issue if the problem persists.

**Closed by anirudhacharya** 2018-03-31 18:08 UTC
Labels: bug, critical, triaged
