### ISSUE TITLE
cuDNN batch-norm precision handling

### ISSUE THREAD

**Issue by ilkarman** [onnx/onnx-mxnet#5] opened 2017-11-28 14:39 UTC
If I try to load a ResNet50 model from Pytorch (loaded with torchvision, exported to ONNX format), MXNet complains that the precision for the batch normalisation layer is too high.

```
!wget https://ikpublictutorial.blob.core.windows.net/deeplearningframeworks/resnet50_feat.onnx
sym, params = onnx_mxnet.import_model('resnet50_feat.onnx')

```
```
RuntimeError: simple_bind error. Arguments:
input_0: (32, 3, 224, 224)
[14:37:06] src/operator/./cudnn_batch_norm-inl.h:49: Check failed: param.eps >= 1e-5 (1e-05 vs. 1e-05) CuDNN requires eps to be no less than 1e-05
```

**Comment by Roshrini** [comment] 2017-11-28 17:55
Thanks for trying it out. trying to reproduce the issue. Did you get this error while running following step?

"sym, params = onnx_mxnet.import_model('resnet50_feat.onnx')"

**Comment by lupesko** [comment] 2017-11-28 18:30
Looks like MXNet's BatchNorm requires epsilon to be no less than 1e-5. Looks like the value in the model is 9.99e-6
See [here](https://mxnet.incubator.apache.org/api/python/symbol.html#mxnet.symbol.BatchNorm) for more details.

When we ran this on CPU context, though, things are fine. This is a CUDNN restriction.

Prioritizing for fix, assigning to @Roshrini

**Comment by spidyDev** [comment] 2018-02-20 23:08
@ilkarman  Could you make sure that ONNX model is generated using the latest ONNX version(1.0.1).
There were ONNX operator changes.  
Also , please rerun the test with the latest version of MXNet, and let us know if you still see encounter the issue.

**Closed by spidyDev** 2018-02-20 23:08 UTC
Labels: gpu, triaged
